spring.application.name=distribution_backernd

# Database Connection Settings
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5434/distribution_track}
spring.datasource.username=${DB_USERNAME:ibo}
spring.datasource.password=${DB_PASSWORD:ibo}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Security Settings
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250655368566D5971}
jwt.expiration=${JWT_EXPIRATION:86400000}